### ISSUE TITLE
Completar Docker

### ISSUE THREAD

**Issue by rmartinsanta** [URJC-CP/iudex#10]
Crear contenedores para cada parte de la app, y crear un Docker Compose que despliegue la APP entera. 

Referencia: 
- https://docs.docker.com/compose/
- https://github.com/rmartinsanta/spring-lti/blob/master/docker/videoquizz/docker-compose.yml
- https://github.com/moby/moby/issues/25562
- https://codefresh.io/docker-tutorial/create-docker-images-for-java/

**Comment by rmartinsanta** [comment]
Esta issue es fácil de implementar, te cuento un día por Teams rápidamente como.

**Comment by Sourius** [comment]
https://docs.docker.com/compose/
https://github.com/rmartinsanta/spring-lti/blob/master/docker/videoquizz/docker-compose.yml

**Comment by Sourius** [comment]
Crear docker compose para poder arrancar los servicios (bbdd mysql 8, rabbitmq, backend):
- backend con build, las dependencias (otros servicios), los puertos y volumenes
- rabbit 
- bbdd mysql 8 con volumenes

**Comment by Sourius** [comment]
hecho y listo para review.
