### ISSUE TITLE
Add Transactional and Delete saves

### ISSUE THREAD

**Issue by rufinogs** [URJC-CP/iudex#110]
Modificar los métodos los cuales no tienen transactional y eliminar los saves ya que no debería de depender de ello. aplicando el @transactional hacemos que se ejecute el método al completo y si falla algo se descarte lo anterior y no se guarde en la bbdd. por el contrario si se ejecuta y todo es correcto se guarda automáticamente sin necesidad de los saves.

**Comment by isaaclo97** [comment]
Realizado en la Pull Request #107.
