### ISSUE TITLE
Autenticación y Autorización

### ISSUE THREAD

**Issue by rmartinsanta** [URJC-CP/iudex#133]
## Contexto
El juez actualmente diferencia el rol del usuario para demostrar su funcionalidad utilizando mayúsculas y minúsculas en el nombre de los usuarios. Por otra parte, disponemos de un servidor Keycloak que permite delegar la gestión de los usuarios a otros proveedores de identidad.

## Objetivo
Añadir autenticación delegada al juez, utilizando Keycloak como proveedor de identidad, y usando preferiblemente el protocolo OpenID Connect. Por suerte, existen múltiples librerías para Java, y concretamente Spring, que implementan la funcionalidad más delicada. Me basaría en la siguiente guía para realizar la implementación: https://www.baeldung.com/spring-boot-keycloak
Asume que el servidor Keycloak existe y está correctamente configurado. Te enviaré los datos del cliente por privado.

## Información relevante
Nota importante: el protocolo OpenID Connect está construido sobre OAuth2, puede ser lioso en algunas documentaciones / tutoriales.

https://www.baeldung.com/spring-boot-keycloak
https://www.baeldung.com/spring-security-openid-connect#introduction
https://www.youtube.com/watch?v=996OiexHze0
https://www.youtube.com/watch?v=GyCL8AJUhww

## Pasos a seguir

- [x] Parte 1: usar librerías existentes de Spring Boot para verificar el funcionamiento de OpenID Connect contra Keycloak. Completado cuando se pueda recuperar datos del usuario como su email y sus roles.
    * #147
- [ ] Parte 2: añadir login / logout y generación de los tokens necesarios para integrarlo con el juez y el frontend.
    * #148 
    * #149
- [ ] Parte 3: añadir control de acceso a todos los endpoint de la API, utilizando Spring Security. Los clientes deberán utilizar el header [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) para realizar peticiones a la API.
    * #150

**Comment by xIvqn** [comment]
> ## Contexto
> 
> El juez actualmente diferencia el rol del usuario para demostrar su funcionalidad utilizando mayúsculas y minúsculas en el nombre de los usuarios. Por otra parte, disponemos de un servidor Keycloak que permite delegar la gestión de los usuarios a otros proveedores de identidad.
> ## Objetivo
> 
> Añadir autenticación delegada al juez, utilizando Keycloak como proveedor de identidad, y usando preferiblemente el protocolo OpenID Connect. Por suerte, existen múltiples librerías para Java, y concretamente Spring, que implementan la funcionalidad más delicada. Me basaría en la siguiente guía para realizar la implementación: https://www.baeldung.com/spring-boot-keycloak Asume que el servidor Keycloak existe y está correctamente configurado. Te enviaré los datos del cliente por privado.
> ## Información relevante
> 
> Nota importante: el protocolo OpenID Connect está construido sobre OAuth2, puede ser lioso en algunas documentaciones / tutoriales.
> 
> https://www.baeldung.com/spring-boot-keycloak https://www.baeldung.com/spring-security-openid-connect#introduction https://www.youtube.com/watch?v=996OiexHze0 https://www.youtube.com/watch?v=GyCL8AJUhww
> ## Pasos a seguir
> 
>     * [ ]  Parte 1: usar librerías existentes de Spring Boot para verificar el funcionamiento de OpenID Connect contra Keycloak. Completado cuando se pueda recuperar datos del usuario como su email y sus roles.
>       
>       * [Verificar funcionamiento OpenID #147](https://github.com/URJC-CP/iudex/issues/147)
> 
>     * [ ]  Parte 2: añadir login / logout y generación de los tokens necesarios para integrarlo con el juez y el frontend.
>       
>       * [Login / logout #148](https://github.com/URJC-CP/iudex/issues/148)
>       * [Generación tokens #149](https://github.com/URJC-CP/iudex/issues/149)
> 
>     * [ ]  Parte 3: añadir control de acceso a todos los endpoint de la API, utilizando Spring Security. Los clientes deberán utilizar el header [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) para realizar peticiones a la API.
>       
>       * [Añadir control de acceso en endpoints de la API #150](https://github.com/URJC-CP/iudex/issues/150)

Actualizado para añadir las nuevas tareas derivadas creadas.
