### ISSUE TITLE
Crear método /me /profile (información del usuario)

### ISSUE THREAD

**Issue by isaaclo97** [URJC-CP/iudex#163]
El fronted necesita obtener detalles de un usuario cuando se tiene un token, como pueden ser los roles.
Es necesario la implementación de un método en el backend para facilitar esto.

**Comment by AdayaUwU** [comment]
Añadir al endpoint las estadísticas del usuario

**Comment by xIvqn** [comment]
> Añadir al endpoint las estadísticas del usuario

Añadido en 6b22a60 . Se obtienen mediante el mismo `/user/me` .
