### ISSUE TITLE
Añadir endpoint para devolver los concursos en los que participa un usuario dado su id

### ISSUE THREAD

**Issue by AdayaUwU** [URJC-CP/iudex#173]

**Comment by xIvqn** [comment]
En 4dc13ac se han creado 3 puntos de servicio nuevos:

* `/API/v1/user/{id}/contests/participating` para obtener los concursos en los que participa.
* `/API/v1/user/{id}/contests/created` para obtener los concursos que ha creado.
* `/API/v1/user/{id}/contests` para obtener los concursos en los que participa **y** ha creado sin duplicados.
