### ISSUE TITLE
Falta información sobre los problemas en las llamadas 'Get contest with full problems' y 'Scoreboard'

### ISSUE THREAD

**Issue by AdayaUwU** [URJC-CP/iudex#177]
En 'Get contest with full problems' no se devuelve time limit, memory limit ni color. 'Scoreboard' no devuelve el color. Implementándolo se pueden reducir las llamadas a la API desde el front.

**Comment by xIvqn** [comment]
Información sobre problemas de un concurso añadido en 2c5f0c3838486a3fe2307ba84042b4259c1198a1
