### ISSUE TITLE
Utilizar SW de pruebas como Jenkins

### ISSUE THREAD

**Issue by Sourius** [URJC-CP/iudex#39]
Para que sea mas sencillo realizar las pruebas seguramente nos conviene utilizar jenkins o algo parecido donde podamos subir codigo de prueba y obtener veredicto sobre como han ido las pruebas.

En jenkins se pueden realizar pruebas automaticas. Se sube el codigo y jenkins lo ejecuta.
Hicimos algo similar en AIS con patxi.

Habra que investigar como se puede hacer todo esto:
- preparar el entorno de jenkins para poder ejecutar las pruebas
- etc

**Comment by rmartinsanta** [comment]
Listo, los tests fallan en integración continua:
https://github.com/URJC-CP/iudex/runs/2818812820

Echale un ojo cuando puedas, recordatorio los resultados del análisis de Sonarcloud deberían aparecer aquí cuando pasen los tests:
https://sonarcloud.io/organizations/urjc-cp/projects

**Comment by Sourius** [comment]
En proceso
Perdona los errores eran algunos por falta de parámetros (los que hemos añadido a contest) startDateTime y endDateTime.

**Comment by Sourius** [comment]
https://stackoverflow.com/questions/23131747/integration-testing-with-maven-run-jar-before-tests-and-terminate-after/52352811
