### ISSUE TITLE
Separar el evaluador del orquestador.

### ISSUE THREAD

**Issue by rmartinsanta** [URJC-CP/iudex#8]
Separar en dos aplicaciones diferentes el sistema de evaluación de código (para Java, Python3, etc) del Orquestador, deberían ser dos JAR independientes, para en un futuro poder generar contenedores Docker de ellos independientes.

**Comment by rmartinsanta** [comment]
Esta tarea se queda para más adelante

**Comment by Sourius** [comment]
Cierro la issue porque ya esta hecha.
