### ISSUE TITLE
No se muestra Swagger

### ISSUE THREAD

**Issue by misial97** [URJC-CP/iudex#83]
Buenas  @jmcolmenar @rmartinsanta @isaaclo97 @Sourius 

Estaba haciendo tareas pendientes de mi proyecto y al actualizarme y levantar con el docker-compose he visto que swagger no mostraba nada de las APIs.

Lo he solventado en local pero no sabía si subirlo no. Os dejo la linea afectada y mi cambio local por si no os habíais dado cuenta.

https://github.com/URJC-CP/iudex/blob/a078a54756fa1494b82f9b079827b92450407920/src/main/java/com/example/aplicacion/TheJudgeApplication.java#L22

Cambio local:
`return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.basePackage("com.example.aplicacion.controllers.api_controllers")).paths(PathSelectors.any()).build();`

Un saludo

**Comment by misial97** [comment]
Veo que ya se solventó, que esto me paso el otro día

**Comment by Sourius** [comment]
@misial97 Gracias por compartirlo.
Si detectas fallos y los solventas puedes subirlos sin problemas.
Lo bueno sería **subir los en una branca aparte y crear un pull request para que los demás puedan revisarlo**, aunque solo lo revisen @rmartinsanta  o @isaaclo97.
