### ISSUE TITLE
Migrate springfox to springdocs

### ISSUE THREAD

**Issue by rmartinsanta** [URJC-CP/iudex#93]
using the following guide: https://springdoc.org/#migrating-from-springfox

Due to: https://stackoverflow.com/questions/70036953/springboot-2-6-0-spring-fox-3-failed-to-start-bean-documentationpluginsboot

Remove the following line from application.properties when done
```
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
```

**Comment by rufinogs** [comment]
![Captura de pantalla 2022-03-29 a las 17 22 39](https://user-images.githubusercontent.com/61109776/160646816-176646a8-8966-4d53-805a-13c7177f7c15.png)

**Comment by rufinogs** [comment]
![Captura de pantalla 2022-03-29 a las 17 23 33](https://user-images.githubusercontent.com/61109776/160647016-dd7a866d-fbcc-432c-b143-c0ff40c336d2.png)

**Comment by rmartinsanta** [comment]
Sube la rama si no consigues arreglarlo y abre una PR para poder revisarlo.
